name: "Notification to Slack (generic Action)"
inputs:
  channel:
    required: true
  message_body:
    required: true
  slackbot_token:
    required: true
  message_text:
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies for Python code
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install slack_sdk termcolor

    - name: Send notification
      uses: jannekem/run-python-script-action@2f75b0640b8ebbf24de58810e95e0220e5fd323f # v1.5
      with:
        script: |
          import json
          from slack_sdk import WebClient
          from slack_sdk.errors import SlackApiError
          from termcolor import cprint

          raw_message = """${{ inputs.message_body }}"""
          message_body = json.loads(raw_message, strict=False)

          raw_text = """${{ inputs.message_text }}""".strip()
          if raw_text:
            text = raw_text
          elif message_body:
            text = message_body[0].get("text", {}).get("text", "")
          else:
            text = ""

          print(json.dumps(message_body, indent=4))

          client = WebClient(token="${{ inputs.slackbot_token }}")
          try:
            client.chat_postMessage(channel="${{ inputs.channel }}", text=text, blocks=message_body)
          except SlackApiError as error:
            print()
            cprint('Error on calling the Slack API!', 'red')
            cprint('--------------------------------------------------------------------------------------', 'red')
            print(error)
